const karachiData = [
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "CENTRAL",
    district_id: "8",
    tehsil_name: "NAZIMABAD",
    tehsil_id: "1",
    uc_name: "HAJI MUREEED GOTH - 44",
    uc_id: "51",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "CENTRAL",
    district_id: "8",
    tehsil_name: "NAZIMABAD",
    tehsil_id: "1",
    uc_name: "HADI MARKET - 45",
    uc_id: "52",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "CENTRAL",
    district_id: "8",
    tehsil_name: "NAZIMABAD",
    tehsil_id: "1",
    uc_name: "ABBASI SHAHEED - 46",
    uc_id: "53",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "CENTRAL",
    district_id: "8",
    tehsil_name: "NAZIMABAD",
    tehsil_id: "1",
    uc_name: "PAPOSH NAGAR - 47",
    uc_id: "54",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "CENTRAL",
    district_id: "8",
    tehsil_name: "NAZIMABAD",
    tehsil_id: "1",
    uc_name: "AURANGHABAD - 48",
    uc_id: "55",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "CENTRAL",
    district_id: "8",
    tehsil_name: "NAZIMABAD",
    tehsil_id: "1",
    uc_name: "NAZIMABAD NO 1 - 49",
    uc_id: "56",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "CENTRAL",
    district_id: "8",
    tehsil_name: "NAZIMABAD",
    tehsil_id: "1",
    uc_name: "RIZVIA SOCIETY - 50",
    uc_id: "57",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "CENTRAL",
    district_id: "8",
    tehsil_name: "NAZIMABAD",
    tehsil_id: "1",
    uc_name: "GULBAHAR - 51",
    uc_id: "58",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "EAST",
    district_id: "9",
    tehsil_name: "GADAP",
    tehsil_id: "2",
    uc_name: "GUJRO A",
    uc_id: "59",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "EAST",
    district_id: "9",
    tehsil_name: "GADAP",
    tehsil_id: "2",
    uc_name: "GUJRO B",
    uc_id: "60",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "EAST",
    district_id: "9",
    tehsil_name: "GADAP",
    tehsil_id: "2",
    uc_name: "GUJRO C",
    uc_id: "61",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "EAST",
    district_id: "9",
    tehsil_name: "GADAP",
    tehsil_id: "2",
    uc_name: "GUJRO D",
    uc_id: "62",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "EAST",
    district_id: "9",
    tehsil_name: "GADAP",
    tehsil_id: "2",
    uc_name: "GUJRO E",
    uc_id: "63",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "BALDIA",
    tehsil_id: "3",
    uc_name: "GULSHAN-E-GHAZI-1",
    uc_id: "64",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "BALDIA",
    tehsil_id: "3",
    uc_name: "ITTEHAD TOWN-2",
    uc_id: "65",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "BALDIA",
    tehsil_id: "3",
    uc_name: "ISLAM NAGAR-3",
    uc_id: "66",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "BALDIA",
    tehsil_id: "3",
    uc_name: "NAI ABADI-4",
    uc_id: "67",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "BALDIA",
    tehsil_id: "3",
    uc_name: "SAEEDABAD-5",
    uc_id: "68",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "BALDIA",
    tehsil_id: "3",
    uc_name: "MUSLIM MUJAHID COLON-6",
    uc_id: "69",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "BALDIA",
    tehsil_id: "3",
    uc_name: "MOHAJIR CAMP-7",
    uc_id: "70",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "BALDIA",
    tehsil_id: "3",
    uc_name: "RASHEEDABAD-8",
    uc_id: "71",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "SITE",
    tehsil_id: "4",
    uc_name: "PAK COLONY-1",
    uc_id: "72",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "SITE",
    tehsil_id: "4",
    uc_name: "OLD GOLIMAR-2",
    uc_id: "73",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "SITE",
    tehsil_id: "4",
    uc_name: "JANANABAD-3",
    uc_id: "74",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "SITE",
    tehsil_id: "4",
    uc_name: "METROVIL-4",
    uc_id: "75",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "KAMARI",
    district_id: "10",
    tehsil_name: "SITE",
    tehsil_id: "4",
    uc_name: "BAWANI CHALI-5",
    uc_id: "76",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "MALIR",
    district_id: "11",
    tehsil_name: "GADAP",
    tehsil_id: "5",
    uc_name: "MEMON GOTH-1",
    uc_id: "77",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "MALIR",
    district_id: "11",
    tehsil_name: "GADAP",
    tehsil_id: "5",
    uc_name: "DARSANO-2",
    uc_id: "78",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "MALIR",
    district_id: "11",
    tehsil_name: "GADAP",
    tehsil_id: "5",
    uc_name: "GADAP-3",
    uc_id: "79",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "GADAP",
    tehsil_id: "6",
    uc_name: "SONGAL-5",
    uc_id: "80",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "GADAP",
    tehsil_id: "6",
    uc_name: "MAMMARABAD-6",
    uc_id: "81",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "GADAP",
    tehsil_id: "6",
    uc_name: "YOUSIF GOTH-7",
    uc_id: "82",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "GADAP",
    tehsil_id: "6",
    uc_name: "MANGOPIR-8",
    uc_id: "83",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "MOMINABAD-1",
    uc_id: "84",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "HARYANA COLONY-2",
    uc_id: "85",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "HANIFABAD-3",
    uc_id: "86",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "MUHAMMAD NAGAR-4",
    uc_id: "87",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "MADINA COLONY-5",
    uc_id: "88",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "GHAZIABAD-6",
    uc_id: "89",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "CHISTI NAGAR-7",
    uc_id: "90",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "BILAL COLONY-8",
    uc_id: "91",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "ISLAM CHOWK-9",
    uc_id: "92",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "GABOL COLONY-10",
    uc_id: "93",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "DATA NAGAR-11",
    uc_id: "94",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "MUJAHIDABAD-12",
    uc_id: "95",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "ORANGI",
    tehsil_id: "7",
    uc_name: "BALOCH GOTH-13",
    uc_id: "96",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "SITE",
    tehsil_id: "8",
    uc_name: "FRONTIER COLONY-6",
    uc_id: "97",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "SITE",
    tehsil_id: "8",
    uc_name: "BANARAS COLONY-7",
    uc_id: "98",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "SITE",
    tehsil_id: "8",
    uc_name: "QASBA COLONY-8",
    uc_id: "99",
  },
  {
    province_name: "Sindh",
    province_id: "3",
    district_name: "WEST",
    district_id: "12",
    tehsil_name: "SITE",
    tehsil_id: "8",
    uc_name: "ISLIMIA COLONY-9",
    uc_id: "100",
  },
];

export default karachiData;
