export const peshawarData = [
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "Akhoon Abad",
    uc_id: 9,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "Shaheen Muslim Twn1",
    uc_id: 10,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "Shaheen Muslim Twn2",
    uc_id: 15,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "Sheikh Junaid Abad",
    uc_id: 19,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "BHANA MARI",
    uc_id: 181,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "DEH BAHADAR",
    uc_id: 182,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "DERI BAGHBANAN",
    uc_id: 183,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "HAZARKHWANI 1",
    uc_id: 184,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "HAZARKHWANI 2",
    uc_id: 185,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "KAKSHAL 2",
    uc_id: 186,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "LANDI ARBAB",
    uc_id: 187,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "NOTHIA JADEED",
    uc_id: 188,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "NOTHIA QADEEM",
    uc_id: 189,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "WAZIR BAGH",
    uc_id: 190,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "YAKATOOT 1",
    uc_id: 191,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "YAKATOOT 2",
    uc_id: 192,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "Shaheen Muslim Town",
    tehsil_id: 9,
    uc_name: "YAKATOOT 3",
    uc_id: 193,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "ANDERSHEHER",
    uc_id: 143,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "ASIA DABGARI",
    uc_id: 144,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "FAQIR ABAD",
    uc_id: 145,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "GULBAHAR",
    uc_id: 146,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "GUNJ",
    uc_id: 147,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "HASAN GARHI 1",
    uc_id: 148,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "HASAN GARHI 2",
    uc_id: 149,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "HAYAT ABAD 1",
    uc_id: 150,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "HAYAT ABAD 2",
    uc_id: 151,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "JEHANGIR PURA",
    uc_id: 152,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "KAKSHAL",
    uc_id: 153,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "KARIM PURA",
    uc_id: 154,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "KHALSA 1",
    uc_id: 155,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "KHALSA 2",
    uc_id: 156,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "LAHORI",
    uc_id: 157,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "MALAKANDHER",
    uc_id: 158,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "MEHAL TERAI 1",
    uc_id: 159,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "MEHAL TERAI 2",
    uc_id: 160,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "PALOSI",
    uc_id: 161,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "PAWAKA",
    uc_id: 162,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "REGI",
    uc_id: 163,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "SHAHEEN TOWN",
    uc_id: 164,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "SHAHI BAGH",
    uc_id: 165,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "SIKANDAR TOWN",
    uc_id: 166,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "SUFAID DHERI",
    uc_id: 167,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "TEHKAL BALA",
    uc_id: 168,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "TEHKAL PAYAN",
    uc_id: 169,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "TEHKAL PAYAN 2 IRRIG",
    uc_id: 170,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "CITY",
    tehsil_id: 21,
    uc_name: "UNIVERSITY TOWN",
    uc_id: 171,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "MATTANI",
    tehsil_id: 22,
    uc_name: "ACHINI",
    uc_id: 172,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "MATTANI",
    tehsil_id: 22,
    uc_name: "BAZID KHEL",
    uc_id: 173,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "MATTANI",
    tehsil_id: 22,
    uc_name: "MASHOGAGAR",
    uc_id: 174,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "MATTANI",
    tehsil_id: 22,
    uc_name: "MATTANI",
    uc_id: 175,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "MATTANI",
    tehsil_id: 22,
    uc_name: "PISHTAKHARA",
    uc_id: 176,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "MATTANI",
    tehsil_id: 22,
    uc_name: "SARBAND",
    uc_id: 177,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "MATTANI",
    tehsil_id: 22,
    uc_name: "SHEIKH MOHAMMADI",
    uc_id: 178,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "MATTANI",
    tehsil_id: 22,
    uc_name: "SHEIKHAN",
    uc_id: 179,
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: 2,
    district_name: "Peshawar",
    district_id: 3,
    tehsil_name: "MATTANI",
    tehsil_id: 22,
    uc_name: "SULEMAN KHEIL",
    uc_id: 180,
  },
];

export default peshawarData;
