let southkpData = [
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "BANNU",
    district_id: "13",
    tehsil_name: "BANNU",
    tehsil_id: "12",
    uc_name: "AMANDI",
    uc_id: "103",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "BANNU",
    district_id: "13",
    tehsil_name: "BANNU",
    tehsil_id: "12",
    uc_name: "DIRMA KHEL",
    uc_id: "104",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "BANNU",
    district_id: "13",
    tehsil_name: "BANNU",
    tehsil_id: "12",
    uc_name: "FATIMA KHEL",
    uc_id: "105",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "BANNU",
    district_id: "13",
    tehsil_name: "BANNU",
    tehsil_id: "12",
    uc_name: "GHARI SHER AHMAD",
    uc_id: "106",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "BANNU",
    district_id: "13",
    tehsil_name: "BANNU",
    tehsil_id: "12",
    uc_name: "HINJAL",
    uc_id: "107",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "BANNU",
    district_id: "13",
    tehsil_name: "BANNU",
    tehsil_id: "12",
    uc_name: "KHWAJA MAD",
    uc_id: "108",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "BANNU",
    district_id: "13",
    tehsil_name: "BANNU",
    tehsil_id: "12",
    uc_name: "MAMASH KHEL",
    uc_id: "109",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "BANNU",
    district_id: "13",
    tehsil_name: "BANNU",
    tehsil_id: "12",
    uc_name: "SUKARI",
    uc_id: "110",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "BANNU",
    district_id: "13",
    tehsil_name: "BANNU",
    tehsil_id: "12",
    uc_name: "CITY 1",
    uc_id: "111",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "BANNU",
    district_id: "13",
    tehsil_name: "BANNU",
    tehsil_id: "12",
    uc_name: "BANNUCITY2",
    uc_id: "112",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "DIKHAN",
    district_id: "14",
    tehsil_name: "DERA ISMAIL KHAN",
    tehsil_id: "13",
    uc_name: "DERA CITY-IV",
    uc_id: "113",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "DIKHAN",
    district_id: "14",
    tehsil_name: "DERA ISMAIL KHAN",
    tehsil_id: "13",
    uc_name: "DERA CITY-V",
    uc_id: "114",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "DIKHAN",
    district_id: "14",
    tehsil_name: "DERA ISMAIL KHAN",
    tehsil_id: "13",
    uc_name: "GILOTI",
    uc_id: "115",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "DIKHAN",
    district_id: "14",
    tehsil_name: "DERA ISMAIL KHAN",
    tehsil_id: "13",
    uc_name: "KEICH",
    uc_id: "116",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "DIKHAN",
    district_id: "14",
    tehsil_name: "DERA ISMAIL KHAN",
    tehsil_id: "13",
    uc_name: "KOTLA SAIDAN",
    uc_id: "117",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "DIKHAN",
    district_id: "14",
    tehsil_name: "DERA ISMAIL KHAN",
    tehsil_id: "13",
    uc_name: "RAKH MANDHRAN",
    uc_id: "118",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "DIKHAN",
    district_id: "14",
    tehsil_name: "DERA ISMAIL KHAN",
    tehsil_id: "13",
    uc_name: "MURYALI",
    uc_id: "119",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "DIKHAN",
    district_id: "14",
    tehsil_name: "KULACHI",
    tehsil_id: "14",
    uc_name: "HATHALA",
    uc_id: "120",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "DIKHAN",
    district_id: "14",
    tehsil_name: "PAROA",
    tehsil_id: "15",
    uc_name: "MALANA",
    uc_id: "121",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "DIKHAN",
    district_id: "14",
    tehsil_name: "DARAZINDA",
    tehsil_id: "16",
    uc_name: "KOHI BAHARA",
    uc_id: "122",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "LAKKIMRWT",
    district_id: "15",
    tehsil_name: "LAKKI MARWAT",
    tehsil_id: "17",
    uc_name: "CITY 2",
    uc_id: "123",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "LAKKIMRWT",
    district_id: "15",
    tehsil_name: "LAKKI MARWAT",
    tehsil_id: "17",
    uc_name: "AHMADKHEL",
    uc_id: "124",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "LAKKIMRWT",
    district_id: "15",
    tehsil_name: "LAKKI MARWAT",
    tehsil_id: "17",
    uc_name: "TAJAZAI",
    uc_id: "125",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "LAKKIMRWT",
    district_id: "15",
    tehsil_name: "LAKKI MARWAT",
    tehsil_id: "17",
    uc_name: "ISAKKHEL",
    uc_id: "126",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "LAKKIMRWT",
    district_id: "15",
    tehsil_name: "SERAI NAURANG",
    tehsil_id: "18",
    uc_name: "MAMAKHEL",
    uc_id: "127",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "LAKKIMRWT",
    district_id: "15",
    tehsil_name: "SERAI NAURANG",
    tehsil_id: "18",
    uc_name: "SERAI NAURANG",
    uc_id: "128",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "LAKKIMRWT",
    district_id: "15",
    tehsil_name: "SERAI NAURANG",
    tehsil_id: "18",
    uc_name: "THAKHTIKHEL",
    uc_id: "129",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "LAKKIMRWT",
    district_id: "15",
    tehsil_name: "SERAI NAURANG",
    tehsil_id: "18",
    uc_name: "BAKHMAL AHMAD ZAI",
    uc_id: "130",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "LAKKIMRWT",
    district_id: "15",
    tehsil_name: "SERAI NAURANG",
    tehsil_id: "18",
    uc_name: "MARMANDI AZIM",
    uc_id: "131",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "LAKKIMRWT",
    district_id: "15",
    tehsil_name: "BETTANI",
    tehsil_id: "19",
    uc_name: "GANDI",
    uc_id: "132",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "TANK",
    district_id: "16",
    tehsil_name: "TANK",
    tehsil_id: "20",
    uc_name: "DABARA",
    uc_id: "133",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "TANK",
    district_id: "16",
    tehsil_name: "TANK",
    tehsil_id: "20",
    uc_name: "GARA BALOCH",
    uc_id: "134",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "TANK",
    district_id: "16",
    tehsil_name: "TANK",
    tehsil_id: "20",
    uc_name: "GOMAL BAZZAR",
    uc_id: "135",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "TANK",
    district_id: "16",
    tehsil_name: "TANK",
    tehsil_id: "20",
    uc_name: "JATTATER",
    uc_id: "136",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "TANK",
    district_id: "16",
    tehsil_name: "TANK",
    tehsil_id: "20",
    uc_name: "RANWAL",
    uc_id: "137",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "TANK",
    district_id: "16",
    tehsil_name: "TANK",
    tehsil_id: "20",
    uc_name: "SHAH AALAM",
    uc_id: "138",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "TANK",
    district_id: "16",
    tehsil_name: "TANK",
    tehsil_id: "20",
    uc_name: "SHEIKH UTTAR",
    uc_id: "139",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "TANK",
    district_id: "16",
    tehsil_name: "TANK",
    tehsil_id: "20",
    uc_name: "TANK CITY",
    uc_id: "140",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "TANK",
    district_id: "16",
    tehsil_name: "TANK",
    tehsil_id: "20",
    uc_name: "TANK CITY 2",
    uc_id: "141",
  },
  {
    province_name: "Khyber Pakhtunkhwa",
    province_id: "2",
    district_name: "TANK",
    district_id: "16",
    tehsil_name: "TANK",
    tehsil_id: "20",
    uc_name: "TATTA",
    uc_id: "142",
  },
];

export default southkpData;
// console.log(southkpData);
